package Inside_Outside
  with Pure
is
   --  Floating point representation for probabilities.
   --  Unconstrained to avoid constraint errors during intermediate calculations.
   type Real is new Long_Float;

   type Non_Terminal_Id is new Positive;
   type Terminal_Id is new Positive;
   type Sequence_Index is new Positive;

   --  Sequence of observations (terminals)
   type Observation_Sequence is array (Sequence_Index range <>) of Terminal_Id;

   --  Matrices for grammar probabilities
   type Unary_Prob_Matrix is array (Non_Terminal_Id range <>, Terminal_Id range <>) of Real;
   type Binary_Prob_Matrix is array (Non_Terminal_Id range <>, Non_Terminal_Id range <>, Non_Terminal_Id range <>) of Real;

   --  Grammar representation (Probabilistic Context-Free Grammar in Chomsky Normal Form)
   type Grammar (Num_NT : Non_Terminal_Id; Num_T : Terminal_Id) is record
      Start_Symbol : Non_Terminal_Id := 1;
      Unary        : Unary_Prob_Matrix (1 .. Num_NT, 1 .. Num_T) := [others => [others => 0.0]];
      Binary       : Binary_Prob_Matrix (1 .. Num_NT, 1 .. Num_NT, 1 .. Num_NT) := [others => [others => [others => 0.0]]];
   end record;

   --  Matrix to store Inside and Outside probabilities (Non-Terminal, Start_Index, End_Index)
   type Dynamic_Matrix is array (Non_Terminal_Id range <>, Sequence_Index range <>, Sequence_Index range <>) of Real;

   --  Exceptions for invalid states or mathematical impossibilities
   Grammar_Error     : exception;
   Computation_Error : exception;

   --  Variant 1: Compute Inside Probabilities (Alpha)
   --  Calculates the probability of a non-terminal generating a specific span of the observation sequence.
   function Compute_Inside
     (G     : Grammar;
      O_Raw : Observation_Sequence) return Dynamic_Matrix
     with
       Global => null,
       Pre    => O_Raw'Length > 0,
       Post   => Compute_Inside'Result'Length (1) = G.Num_NT and then
                 Compute_Inside'Result'Length (2) = O_Raw'Length and then
                 Compute_Inside'Result'Length (3) = O_Raw'Length;

   --  Variant 2: Compute Outside Probabilities (Beta)
   --  Calculates the probability of the sequence excluding the span generated by a specific non-terminal.
   function Compute_Outside
     (G     : Grammar;
      O_Raw : Observation_Sequence;
      Alpha : Dynamic_Matrix) return Dynamic_Matrix
     with
       Global => null,
       Pre    => O_Raw'Length > 0 and then
                 Alpha'Length (1) = G.Num_NT and then
                 Alpha'Length (2) = O_Raw'Length and then
                 Alpha'Length (3) = O_Raw'Length,
       Post   => Compute_Outside'Result'Length (1) = G.Num_NT and then
                 Compute_Outside'Result'Length (2) = O_Raw'Length and then
                 Compute_Outside'Result'Length (3) = O_Raw'Length;

   --  Helper: Compute the total probability of observing the sequence given the grammar.
   function Sequence_Probability
     (G     : Grammar;
      O_Raw : Observation_Sequence) return Real
     with
       Global => null,
       Pre    => O_Raw'Length > 0;

   --  Variant 3: Expectation-Maximization (EM) Step
   --  Calculates expected counts and updates grammar rule probabilities to maximize the likelihood.
   function EM_Step
     (G     : Grammar;
      O_Raw : Observation_Sequence) return Grammar
     with
       Global => null,
       Pre    => O_Raw'Length > 0,
       Post   => EM_Step'Result.Num_NT = G.Num_NT and then EM_Step'Result.Num_T = G.Num_T;

   --  Helper: Validate that for every non-terminal, the sum of all its production probabilities equals 1.0.
   function Is_Valid_Grammar (G : Grammar) return Boolean
     with Global => null;

end Inside_Outside;
